version: "2"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
    environment:
      - REUSE_KEY=true

  weechat:
    image: pschwartz/docker-weechat:latest
    container_name: weechat
    ports:
      - "9022:22"
      - "9001-9021:9001-9021"
      - "60000-60050:60000-60050/udp"
    env_file:
      - ./weechat.env
    environment:
      - VIRTUAL_HOST=weechat.progmad.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9001
      - LETSENCRYPT_HOST=weechat.progmad.com,znc.progmad.com
      - LETSENCRYPT_EMAIL=philip@progmad.com
    volumes:
      - weechat:/home/docker/.weechat:rw
    networks:
      - proxy-tier

  znc:
    image: stanback/alpine-znc
    container_name: znc
    ports:
      - "6697:6697"

    links:
      - bitlbee:bitlbee
    env_file:
      - ./znc.env
    environment:
      - VIRTUAL_HOST=znc.progmad.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=weechat.progmad.com,znc.progmad.com
      - LETSENCRYPT_EMAIL=philip@progmad.com
    volumes:
      - znc:/var/lib/znc:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy-tier

  bitlbee:
    image: stanback/alpine-bitlbee
    container_name: bitlbee
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - bitlbee:/var/lib/bitlbee:rw
    networks:
      - proxy-tier
  

volumes:
  bitlbee:
    driver: local
  certs:
    driver: local
  weechat:
    driver: local
  znc:
    driver: local

networks:
  proxy-tier:
    external:
      name: nginx-proxy
